spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: administrator
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
  web:
    resources:
      static-locations: file:${batch.output.directory:target}

batch:
  # 1) Base query settings
  base-query: SELECT id, name, email FROM user
  default-where-clause: WHERE id is not null
  
  # 2) How many rows per transaction/page
  chunk-size: 500
  page-size: 100

  # 3) Output file settings
  output:
    # directory (absolute or relative); defaults to 'target' if blank
    directory: target
    # you can use the token {timestamp}, which will be replaced at runtime
    filename-pattern: export-{timestamp}.txt
    # include the header row (column names) if true
    include-header: true
